# Метаинформация
name: "cluster2_genetic_optimization"
description: "Оптимизация промтов для кластера 2"

# Настройки данных
data:
  file_path: "data/raw/df_ipipneo_120_clusters"
  clusters: [2]
  num_participants: 3 # train:мин30-50 test:40 # посчитать сколько по токенам затраты
  save_every_n: 2

# Настройки модели
model:
  model_name: "Qwen/Qwen3-235B-A22B-Instruct-2507" # MiniMaxAI/MiniMax-M2 #Qwen2.7 или Deepseek(Gigachat3)
  provider: "cloud"
  temperature: 0.7

# Настройки EvoPrompt
evolution:
  algorithm: "GA"  # GA или DE
  population_size: 1 # поколений 4, 6, 10
  num_generations: 1 # 3, 5
  mutation_rate: 0.15
  crossover_rate: 0.8
  selection_method: "tournament" # tournament, roulette
  
  # LLM для эволюции
  llm_for_evolution: "Qwen/Qwen3-235B-A22B-Instruct-2507" # gpt-3.5-turbo
  provider: "cloud"
  temperature: 0.7
  
  # Что оптимизируем
  genotype_params:
    role_definition: true
    trait_formulations: true
    facet_formulations: true
    intensity_modifiers: false 
    critic_formulations: true 
    template_structure: false


# Настройки эксперимента
experiment:
  seed: 2026
  save_every_generation: true